version: 2.1
orbs:
  node: circleci/node@1.1.6
  coveralls: coveralls/coveralls@1.0.6
jobs:
  strava-package:
    working_directory: ~/project/packages/strava
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov.info
  strava-maps-app:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
  strava-maps-app:
    jobs:
      - strava-maps-app
  strava-package:
    jobs:
      - strava-package
