query {
  getStravaActivities {
    id
    name
    distance
    time {
      moving
      elapsed
    }
    elevation {
      gain
    }
    type
    startDate
    startPosition {
      lat
      lng
    }
    kudos
    polyline
    speed {
      average
      max
    }
    heartrate {
      average
      max
    }
    prs
    achievements
  }
}
