import { ParsedStravaProfile } from '@tokks/strava'

const athleteId = '80690783'

const diego: ParsedStravaProfile = {
  createdAt: '2015-11-21T00:38:38Z',
  id: athleteId,
  name: 'Diego Zancaneli',
  picture:
    'https://lh6.googleusercontent.com/-dBdEU9qxwJk/AAAAAAAAAAI/AAAAAAAACOQ/AMZuuckvdmuhZtXGNE8-uvLhhWw4xnwikQ/s96-c/photo.jpg',
  username: 'mtokarnia',
}

export const diegoActivitiesV3 = [
  {
    athleteId,
    distance: 6175.6,
    elevation: {
      gain: 43.3,
    },
    id: '5583663958',
    name: 'Corrida matinal',
    pace: {
      average: 334,
    },
    polyline:
      'p`}nC~dx{GpAu@JGDFFD@FDD@A@F@DBB?B?FCB?D@B@FBBBB@B@@BBBB@BBD@B@DDBBBBDBDBB@BBHDF@BFDBD@B?BA@A?C?C?C?C?EAA@E?C?C?C@C??BC@C?C?C@ADE@EBEBEDCDCDADCBCBADCDCDCDAFCDAFCDADCDAFAF?D?DADADAFADADADAD@D?D?F?F@F?D@F?D@F?FAZCB@?@D@FBD@F@F@D@DBF@F@F@D@DBH@BBDBD@DBFBBDBBDBDBD@DBD@@BDDB@@DBBBD@DBD@D@D?FBD@D@FBD@F@@?D@B@BAD?D?FB@?D@D?D@BBFBBBD@D@@@D?DAD@F@DBD?D?F@@?DBFBB@F@F@F@D@D?F?B?D?D?B@D@DAF@@?D?D?F@D?D@B?D?D?D?D@D@D?D?F?@?FAD?B?F@@?FBBAF@B?D?D@D@F@D@D@D?D?FAB?D@F?@@D@D@B?DAF@D@D@D@D?FADAF?DAD?D@D?D@D?F@@@F?F?F@B?DBB?F@@AFA@?D?D?D?DADADADCBAFCDCFADCFCBADAFC@AFCBCFC@ABCDE@?HA@ADAB?@AB@DA@ADCFABAFA@?D?BAD?D?D?D?D?F?B?D@D@B?D@@?D?B?F@B@F?D@BDDBB@FB@?D@FAD@D?D@D@F?BAD?DCDCFCDAFEDCDADCDADCDADEBCFE@CDCDADCDADADCBCDADEDADCBAFE??FC@ADA@ADC@ADC@A@EBC@G@A@G?A@G?A@E?G@GBE@E@G@E@E?E@E@G@E@EBEBCBEBEDCDCDE@ABCBG?ABEDEBEBE@GBCBCDCBEBC@ADC@?DCDCBADADC@ADABCDCBCDC@?DGBABCBEBCDCBEDCDADCDCDCDCBADCFCDEBCBEBG@CBE@E@G@E?E@G@EBE?G@E?E?GEEAGAECGACAEAGCECG?CCEAECGAE?CCE?ACEAACCAEEEAACECCEEEEEGCCCCAEEECCAACCEEEEEECCCCECECCCAACGAACECGCCAEEGAACCEECACEAAEEAAECAAEE?ACCCEAEAACGACCE?CCCAECECEAEGECEAACGAACGAECEAEAC?E?AAGAAAEACAGAAAG?GAAAG?AAGAGAEAGAEAEAG?ACGAAAEAECE?ACECCCIAAAECECCCECCAAAECEAACEEGCCCECCCECECECEAAAAACECEAECCCGCCEA?EEAAEAECAAAAAAECEAEACAE?GAI@G@E?E?G@E?EAG@A?G?E@EBE@E@A?EAE@CBG@GBC@E@CBEBCBEBCDEBCDEBEDA@CBEBCBE@EBCBEBCBCBEDCBA@EBCBCDCBCDCBCBCDEDC?EDA@EBCBCDCDCDEBE@EDCBEBCDEBEBA@EDA@EDA@CFA@CBCDC@CFA@ADCDADCDCBCDCDA@CBA@EFA@CBABCBEBCBCDCBAFCDEDCB?FADAD?DCF?@CFA@AD?DAFCDADAD?FAFAF?D?FADADAF?B?F?B?DAF@F@D?H?BADAF?F@@?F?@AD?FAF?@CD?BCDADCDADAD@DAD?DAH?@ADCFA@?F?BADAFAF?BCDCDA@CDA@CD?@CFA@CDA@CBCFABADCBCBCBEBEBEBE@E@EBEBE@E@E?E@A?G@E?A?G?C?G?AAGAA?GCAAGEAAECEAE?GAA?CAA?GAA?GAAAG?A?EAA?ECA?CAAAEEAAECCCEEAACEACECCECCECEEAAECGECAECECEAG?EAE?EAG?C?G?E?G@A?G@E@EBG@E@E@C@EBEDA?EBE@A@EBA?G@A@E@CBEBA@E@C@EB?@EBCBCDCFEBCDADGDCDGH?D?BCBAFCFCDCDAH?BCF?@AFADAFAD@F?F?D@HAD@D?D?F@D?F@D@F?B@D@F@F?B?D@D@D@F@DBF@D@F@DBD@F@DBDBD@DBDDD@DDD?BBBDD@@BBBBDD@BDBDBDBF@@?B@FB@@D@BBFB@?F@@?D?B@D?@?F@@?DB@@F?B@D?B@F?D@DBHB@?F@FBD@B@F@DBD@D?D?D@DBD@F@B?H@B?D@D?DAF?@?D?FBB?D@F?@?D?H?@@FA@?F@@@D@D?B@D@B@F?B@F?@?F?@?D@D?D@B?F@BAF?@?D@D@D?F?D?D?H@@?D?D?F?@@F?@?D@D@F?D@F@B@D@F?BAF@D@DAD?D@F@@?D@F@B?D?F@@?F@B?F@B?DADAFAB?FCHAFAFADADAFABCDADCDCDADABADCBCDCDCBCDCDC@ADABADA@?F?@AFA@ADADC@?F?B?B?F?B?F?@?F?@?H@@?F?D@@?F@@@F@@?FB@?D@D@@?F@F@F@@@BB@?F@@?F@@?D?F?@?F?F?DAHCDCDCFCDCBAFC@AFE@CDADEBADADE?ADCBCDCDADEDCDCDC@?DC@ADCDCDC@EBCFC@?@EDEDE?ADE@ABE?ABG?ABG@C@E@E@E@EBE@A@G?A?EBG?A@G?A@E@E@GBEDEBE@EDG@A@E@?BC@ABCBEDADEDCDCDCDE@ABC@ADABCDE?AFC@ADC@?DEFCBADADE@?DC@ABCDCDC@ADEBADEBCDCBEDCFC@CFC@ADCBCDE@A@G@G@G@E?I?C?C?G?C@AAE?EAGAGAC?E?GAG?CAGAAAECICEAE?CCG?EACAEACAGACEEAAEE?ACCECCEAAECCEAECECEEEAACCEEAAGEA?CECCEECCCECCCCECAAEEAAEECECCCCCECCEECCCGCCACEEAAEACGAAAEAAAGACCECCAEAGAEEGCEAAAEACCGAAAECC?G?AAG?CAEAEAEAGAAAGCEACCIAEAIACCCCE?CAEACAEAGCCAGACCEAACEAACECGCECEAECEAECEAACGAACEACAEAAACAEACCECEAACCEEAAECECCCEECACCEEEEEAECCAGCAAECC?EAAAEAEAE?EAE?GAI@EAA?G@E?G?E@G@C?E@EBGDA@E@GDCBE@CBEBGBA@EB??EBCDEDA@CDEBE@A@GBEDCBCBEDEBCBCBCDEBA@CDCBEDC@CBCDCDEBC?CBEBCDC@EBCDEDA@EDA@GBA@EDC@EDA@EDC@ADEBADCDCDA@CBEFA@CBEDA@ADCDCDABADCFA@CDA@AD?BCDCDEDABEDABCDAFCBCFA@CBAFADCF?BCDAFADAD?@CBAFAB?F?F?FAFAF?@AH?DAFABAF?@?FAB?DAD?FAF?@?D@H?BAD?F?@?F?BAF?@?F?@AD?FADAF?DAF?FA@AF?DAF?@AFA@?DAFADADCFADCFA@CFAB?@CBCBCBCBCDEDA?EBC@CBEBEDA?CBGBA@C@A?EBA@G@C?ECE?ECE@C?E?A?E?A?GCAAECEAA?EAEAA?EAG?A?GAA?EAA?GCE@ECEAEAE?CEAAEC?AECCCCEECAEEECEACCCECCCECEACEGCEAEAGACCEAAAGAA?GAIAA?C?GCAACAGAAAEAA?A?ECAAACAAACAAECA?CAA?EAA?ECA?EEAACCCACCECCCCECCAEEEAAEEACCE?ACE?AEEECCCCGEE??CECCCGAACGACAIACCG?M?K?M?K@G@EBEDCBEBE?A?E?E@G?G@E?GBG?A@E@E?E?A@GAA?EAGAI?EAGAECECEEEACCCCEEA?EAECECCEAE?E?EEAACCECCAG?C?GAC?E?C?G?E?E?G@G?A@E@GAA?C@E?E?G?A?E?E?G@G?A@G@E?CBE@E@A@G@A@E@EDA?G@?@E@EBA?E@A@E?E@A?EBC?E@C@C@A@ABA@@@qAY[SPBBF@?EGCA?AA?AEACCEAC?ECIAEAECECECCCCCCCECECEACCCCECGAGAECGAEAGAEAEACEAAAC?C?CACC?ACCGKEGEGGIEGEGGIAEAEEGACCE??CEAA@G?A?GAA?EAACEAAAEEEEECEACCE??CGACCCCGAACCCGAAAECGCEAECG?CCCAGAEAG?ACE?ACEAACGACAECEAECEAEAGAACGEGAACG?CCGAACGAACEAEAAEECCAEACCECE?AECA?CEAACE?AGIAECECCAEAECEAACG?ACEAAECAACEAACEEECEAACG?A?GCEAGAEAGAE?EAGAECEAAACAACG?ACEEGAACECCCGCECCCECEACAEAEAGECAAACAA',
    startDate: '2021-07-06T11:26:15Z',
    startPosition: {
      lat: -23.582972,
      lng: -46.659517,
    },
    time: {
      elapsed: 2125,
    },
    type: 'Run',
  },
]

export default diego
