import { ParsedStravaProfile } from '@tokks/strava'

const athleteId = '5587011978'

const julia: ParsedStravaProfile = {
  createdAt: '2015-11-21T00:38:38Z',
  id: athleteId,
  name: 'Julia Iurko',
  picture: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/48302659/20418242/1/large.jpg',
  username: 'mtokarnia',
}

export const juliaActivitiesV3: any = [
  {
    athleteId,
    distance: 9010.0,
    elevation: {
      gain: 19.0,
    },
    id: '5605817412',
    name: 'Lunch Run',
    pace: {
      average: 414,
    },
    polyline:
      'rqunCjgc|G?ABQWa@GKKICCOKKIIS@IHIJCZ?DADAJ?DDB?TADAPGRGBANGPILERSDCd@ONQRUX]V]@@??FE@A@E@CBIBABE@G@ER[\\MR[NO\\WDARMJSV]HG@CDGFIR[RWBADEBCNWZYNSRIFCPWJMLWLO@C@AROPM@C@I@GDGHITWJKDEBGBIBG@?BALMBGNM\\[?CFKTOBCTYT_@TWV_@BCHUR[R]T_@BGHADAZCTEJ@DAZENBFCDCZI\\CB@DDLFHHZ\\@BNRHFFJLP@BRRZX@DAHGFCDIPSTW^IDW^W\\CBYTYX[XORGHGDC?AAKGCAGAEA[QKKIIEAO@W?KBAFP\\BBHLNLHDLBXHBJAD[^[XU^CBUXMVIFKJYV]ZSZEFMN_@RUZ[PUTKNA@S^UZSNGDGHQRS^WZCBEBOHW^IDIHEJGFC@A?WESWICAASQOICCEAU?ADSPYNUNWREDGJKHEDUZUR]RYRC?KB_@BSBMAC@SHYJCBMFI?WHEAKE]UEGYMQQ]YCCCI?K@EHODAHB`@@ZBZEBAZI^KTITIFEDCB?NOTWTYZYBCZSVYNULGBAPSVa@T]TMT]X[HMTUV_@BCPSRUFGFGHIJMVGB@JJ@@DBD@VXTPBDDJBDAH?FGJEFOLE@IDA@IN?BADGFU\\A@OLIFKH[\\YXSVQNABQRQPCBUZSXO\\WNQNWZW\\WRSPABWLK@I?Q@CB_@Pa@T_@De@HI@YI]SIISQUO[Y?UDOHER?P?@?\\GF?B?HAD?LCRC\\C^O^Q\\UTSTYX]Z]JMJI\\WFDHDLBL?HBLB@@?DBF@@DBLN@BB?DAFAH?BCBCDA?A@?BCBC@?@C@A??BC?ABCFG@AFI@CDGTO@CLMFABIFCHEHG@ABEBAHQ@ALK@GBKFK@?RKNODCDC@APKHY@QBGJM@A@CJEVO?A?IFAPMLMDIDIJQ@AF?@AFK@ABEDELQBCFKBABCLIFGBCBAFGB?BA@A@CRUJM@E@C@C@C?I@CAECKIOC?AA?CACEK?A?ACIAGIIQMAAAA?E@CBG@A?AFI@CRUN[N[@ADK@EDGFM@M@U@EBKESACI?IBUBc@HUDE@QFG@SAC?UBC?GDC@GBA@@NFLBD?@BD@BR^BDT^RRPT@BJZBBFLLNB@VRD?NBD?F?PBTJ@@HJ?DPT\\HRBPP@BEFIJMBUEC?QMYQQCWIQGSPYHQJCDQLSTMFCBS^GHGFU^Y^QV]ZA@QJC@C@OLGTCJADOPCBOHCBEBIFURAFCBILSPURQVUN]^OPW\\QZOTEDOZC@EDA@KJKLADUVUVEDCBKHWRUPEBSLC@YJIBO@_@LWHQDMBC?e@Ja@I_@QOMWOQUQQCGAIBMBCNGVKD?RBBBPB@Ah@IB?ZI`@K\\KXSPYTYJILOXWVURQNO@CBOACKIKGAAUYACDGBCBABDFRBFHBDJFEBADADC@CBABC@Ah@a@X]BANQX]FERWPODGBGBALOBADA@ABCLQNQVQVUJSZYJOPQBCPSPWPU\\]BCV[DKBAPSX[DEPOBABCLED@TFLPB@JJFFTT@J?HCJEDCBMNCHMHC@EFABSVOVEJGHOLA@CHA@@FOPUZ[XA@CBIFKRMLC@IJA?IFEDIH?DA@CBKNGJC@CDCDCDGDKJABA@C@A@A@ABABABQPC?GFKFMXULA@MHA?A@CBIJCBIHGFKLCBGDSVC@ODCD?BMPC@EHCDCH?@AFEDA@EDGHEHKFKJADGDADOLQLQLGFMJQHC@MDKFIHQHMDCBGHA@_@HEBOHc@HA?IBUDEA_@SECMKKMCCEEECMIIGW[?WLIZE@?P?B?D?@ARGJCVGB?H@VGXQDCP@LELERMBCRQPMPWTQJMFK@A@A?ABA??@???DE@CFIPS@?@?F?FIDEJUNSBCJKBEFGHKFGHKTWPWVW@APUPOXWV[RSHIJGFMBGBILOFIROTWBCJQR]Z]@AV_@BCJMPU\\YTODCPSLGH@NLLJTTRRFJ?V?DBBH@\\LXJB@@D@J@D@BB@VNJNAHGFEBINABY^SPMNOJQPY\\ABU\\IFGFCBONORSXKJ]ZUTCDIFY\\KFA@SVWVURCBKFCB',
    startDate: '2021-07-10T15:00:15Z',
    startPosition: {
      lat: -23.544741,
      lng: -46.716224,
    },
    time: {
      elapsed: 3728,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 1620.0,
    elevation: {
      gain: 0.0,
    },
    id: '5605340279',
    name: 'Lunch Run',
    pace: {
      average: 333,
    },
    polyline:
      'drunC|fc|G??KKCAOGCAIGEECCGEIGGIACACIIAIAG?IDK@ADATCD?R@BATARG@?NGPGNCRG@AJKHGTIHGHGBCROTS\\UV[BCP]DEPGVOP[V[@CNUBCb@]ZYDEXa@BC\\_@BERWNQ?CNUZM`@Lb@XDDPNLLFTAFQPMPKLCBKLCDSVW^CDIHSRCDa@RWXUV]\\UBK?GEOYUU[[EEWGCBABERQZ_@^CFY`@IF[ZCB]VKFC@_@L_@DI@UF[Fe@BI?ED]?WDEH@JTTJH\\ZHJVVHJB@F@NDJ?F?`@E\\ILALERKJIFADA@?@ANIRMXUZY@CRSCAA@CF?H@BAB?JULWLWHA@GDQFMD',
    startDate: '2021-07-10T14:44:15Z',
    startPosition: {
      lat: -23.544831,
      lng: -46.716148,
    },
    time: {
      elapsed: 540,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 4810.0,
    elevation: {
      gain: 72.0,
    },
    id: '5601453964',
    name: 'Afternoon Run',
    pace: {
      average: 376,
    },
    polyline:
      'xnunCvcc|GA@BA?A@C@CFKDCTIN?B?BAD?XCLCF?BAFA^M\\KVIFCb@SBAXOTSBCZWBCBGDEDCDEJU@CLKB?DCJKDGJGX[@C@EBCBC@CNQTWT_@FGX]DEHGHIRSLSVUXa@Xa@@CDEHIVUPUTYZ[JIBEJMHOFIJKLMJMLMJKNOLODEFEHKBCV[X[RUT[Re@DGVc@BELUDO@CJQHMHMFCPKRI\\QTAb@Gf@?D@JANCb@IBAPKXId@Gd@Cb@EJAHCPEf@GZBVRJRB?B?FORQRYX]FGTc@BCRM\\CR]Nc@R]Je@JWP[FUHUHODGNe@?E?CHQL[T_@Pa@NWNi@@INYPc@Le@@EL]V[N]JYBQBQRc@Ng@J]Te@Ra@H]Ja@V_@JSNa@Pc@Nc@@ELYHYR_@L]JULU@_@A[H[Lg@J_@AAUBQHG@A@OLMXI\\CJAL?BB\\BHDL@D?DF^?B@XMh@Mh@Qb@ABIPMXOb@S`@GRK\\O`@CHMb@Sd@CHO\\GLSb@AB?DBNC`@A`@KRUPWNE@UROf@ABK`@MXQ^S`@CLMb@EJUd@CDQ^Q`@EFQb@Qb@GFGBK@g@@C?e@BS@c@BC@[L[XCBWVIFC?_@MKF?FDDJFLZAh@@\\Hd@B\\@PGXY^[^QXU\\]ZYVUZCFADGHUVURWTQP[ZAB[^YZSXQTGLGBEBEFGBICQMEA]S[IGCEAKGCAG@CBOFGDQDEB]\\WZ[Z[\\GHY^KNYZGDGHIJONWVYRWZCDQVOVMPGF[ZWZSRUPYTUPCBKRYZGFE@C@SNIDM?CCGKACKWQKGGAAEAAAE@C?GBIFQRWRWPUP_@TC@MHUJ_@R[JO@KDGDWFI@K?WFE@E@I@C?IECASCEAE?K@G@O?WAMAMCE?K?IBI?GBEBMFULGDGDIDI?C?IAAAK@EBEBC@E?SFGBOJID[RC@YRMDKBC@KFGB',
    startDate: '2021-07-09T17:21:15Z',
    startPosition: {
      lat: -23.544287,
      lng: -46.715643,
    },
    time: {
      elapsed: 1811,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 7400,
    elevation: {
      gain: 84.2,
    },
    id: '5587011978',
    name: 'Corrida ao entardecer',
    startDate: '2021-07-06T21:00:00Z',
    time: {
      elapsed: 2777,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 5500,
    elevation: {
      gain: 48.0,
    },
    id: '5594439176',
    name: 'Corrida matinal',
    startDate: '2021-07-08T11:40:00Z',
    time: {
      elapsed: 1919,
    },
    type: 'Run',
  },
]

export default julia
