import { ParsedStravaProfile } from '@tokks/strava'

const athleteId = '7551605'

const mateus: ParsedStravaProfile = {
  createdAt: '2015-11-21T00:38:38Z',
  id: athleteId,
  name: 'Mateus de Pinho',
  picture: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/7551605/20934574/2/large.jpg',
  username: 'mtokarnia',
}

export const mateusActivitiesV3 = [
  {
    athleteId,
    distance: 7168.5,
    elevation: {
      gain: 26.0,
    },
    id: '5583779471',
    name: 'Ibirapuera 9x0:10@3:00/km',
    pace: {
      average: 422,
    },
    polyline:
      'bz|nCj{w{G??NMJIBEDEHIDCHGFEJCLABCJEJILADAD?RFP?J@LDHBNFRHd@N\\FH@RHNJBBBFZZBB^RRJLD`@Ff@@VGD@?@WDe@AE?e@EMEEA_@SCCKKKGYQYKWDQ\\Ad@CPKXMTEDKLGHEFILELCHS`@ABKd@?L?LEZ?VAJ?B@B@RD\\FZPd@P`@LXDHF`@?BBX?BAT?NBRDh@Hd@DJXb@PXFFBBRXB@LFVJHDTJLD`@LD@TD\\FVBJ?d@BB?b@BD@^BTDb@@D@R@TD^Bd@DZD\\BRBD?PBT@L?\\B^Ad@KH?`@SZKDEZOVEDAB?ZGB?\\?PBN?\\BXFH@H?F?J@^AJELIVSNELGTSBCLGJGDEFCNSJUL_@@ODOJ_@BG@ET_@NOHIXSBCRKDAJIHGXYBC\\YBALINMHABCJIFIDY@O@MAa@Ge@Ec@M_@[[GEKGSQWWOKEICAMMIMY_@CA[]CCQc@ACEOEMI[GW?EAEAEG[ESC]E_@?KC[C[@C@@BN?JBTBPFTBHHRDTBh@?R@H@DBHBFBHDRLTBBFH@FBFJLDH?@NRPPBB@@DFXVRTFHHFLNHHJD@DDD@BHF@@BBFBD@DBFH@B?@GCWKEEKMGEQOGIQSIGGIIIQQEGCEIMAAICEECACKEICEEEAAEEGIGEACECAAAAQ]CQGMIUAEAGCMCU?CAAAECGESM]CGCG?CAAB@@@HF?@@B@@@BDF@DLXFVF\\@FBJ@JBJBJTb@HRLPLNBDDHBD@BJPBBNPBBHHNPFNRNFDFBBFHJLLBBJLLV@BD^FLABJ`@@ZJN@?FEPGZMDCPG@?JALG?ABGEEWQc@QWMKEKGSKGEMIEEGEA@BHNP@@FP?@H\\H\\AXAH?D?B?FAJCFIVONKFGBEBMJMLOLEDKFGHKFKFQLGDOLKHA?E@GD?@B?BARS\\YHIHGHGJEHGFEHGLMDGBEBEHMLCDEBADAHEPQJE@AZOD?VIXONGLQ?GA?CAWCKEICICKGUIICGCC?MCIBED?@?@?@FPBBDT?TAFA^AJCHGRQPSNQNGFID]PC@IHIHIFKHCBIFC@MLA@GBA?CBCBEDGFIR?@CBCBCFADAD??CXAFEH?BABKPC@EJGNCFADEDCDADEBGDGFIFCBIFA@KHC@MHIB[JE@C?C?MDUFKBI@M@O?KAi@KEAKAGAC?EAEAA?MCA@E@M@E@S@E?MBEBUBA@G@QBABOJCBYNSHC@SHS@WBI?O?SCEAI?YEE?IC]CGAY?K?IAMAMAKAe@EWCYAUCKAM?EAIAEAMCWG??A?K@I?EAEAGCKAGAEAE?EAIAGCOAC?C?QGECGEAAA?CAGAAAC?EA]IMIQ?A?YOIIGIAEE?CDC@E@G@W@I?Y@MBK@M?S@EAAC?CJGB@@?B@?@A@OD??D@VKHGHGFGFIJS@CFM@EDS?E?ICSASC]?EAQ?SBi@?G@EFU?EDQDG@CXa@V[BCRMBAZKBCJEHAHA\\GL?D?H?B?`@BXNVRXVXLTDD@b@DD@d@F^DB?D?NAb@MVQPUHQL]Ha@Bi@Dk@@I@Y@KB]?MBc@@KDYBOBKDKDWBEPc@@CHKJMTa@BEHQLOV_@X[XYJITU\\YBAZY^YVO\\YXS\\G^F\\@J@NBHDHFBB^V\\VHFLJFPHNFJ@BPh@BDTd@P`@@DF`@Hf@HXHRP\\RXHLVZDFVVBB\\ZBBVTFJDFFDXXJRDHHZLd@@\\A^CVCH',
    startDate: '2021-07-06T11:02:15Z',
    startPosition: {
      lat: -23.581935,
      lng: -46.657984,
    },
    time: {
      elapsed: 3040,
    },
    type: 'Run',
  },
]

export default mateus
