import { ParsedStravaProfile } from '@tokks/strava'

const athleteId = '84932271'

const ste: ParsedStravaProfile & { shortname: string } = {
  createdAt: '2015-11-21T00:38:38Z',
  id: athleteId,
  name: 'Steh s',
  picture: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/84932271/21151180/1/large.jpg',
  shortname: 'Steh s.',
  username: 'mtokarnia',
}

export const steActivitiesV3: any = [
  {
    athleteId,
    distance: 1780,
    elevation: {
      gain: 0,
    },
    id: '5594783714',
    name: 'Corridinha na quadra',
    pace: {
      average: 543,
    },
    polyline:
      'jmxnCha~{GADEHA@C?AA?AAADE@CDCD?@@@F@B@DGBEBEDC?@@?@??ABACCAEECEBCHABCBEBAD?DF@FCFC@G@E@EDA@EACCCE?EFEF?BCFCDEDB?@?FCDC@EBCBEBCBA?EOBEDA?AFCBABEFB@F@FCDC@GBCBA?G@AA?GAACEBE?A@EF?FC@A@FBDBH@D?BIBEBE@G?AE?ACEACBEBADCBCBEDABB@B@F@D?@I@CBEBC@E?AAAEAAAG?CDEFADADCB?DB@@AD@DCDA?A@ABA??@@???A@?AA??AA?C@A??B?A????BABCBEBG?ACCEE?AC@?@A?CBA@??CBA@???@?@?@@@???@B@@@?@B?@@@?@A@ADA??@A@?BA@C?CAEAAEAG?C@GFC@A@?@@F?@DDBA@CBADEBCBC@AAEEC?AG?EDA@GDA@C@@F?DBDFABADGBEDA@C@CCEECA?E@EBEDA@@DBBBBEBA?@?@A@A@ADCFGDA?AEDCBGBEBA@?C@@@ADEFA@ADC@A@CC@A@GDCBEDCBA@E@A?BEBCFCFCDCBE@ACBA?A@GDEBA@EBCB?@@EBCBCFABAFE@A@A?H?AE@GHEBC@CA@A@A@C@A@A@GDA@ADCACC@EDGDE@A@CD?@?E@ABEDCBCDC?A@?C?A@C@A?EDC@CBA@??@ABA@AFADCDC@AB@BF?DCDA@E@C@CBA@A@@?BCDADEDC?EGACECCCDA@EBCBC??BC@BDDB@@BAD?DCBEBC@ABAEGAAAEAAG@ABEDA@CBC@A?A@?H@BBBH@B?BCDCBE@A@E?AEE??ACCAEBAB?@@AA?A?A?A@?@A@BA@ABCBCDC@C@B@BBD@D?@GBKLGDAEEGAC?E@IJCH?BADF?FADEDGACDGEAEAE@EFCFCBAF@@F?FEDCBE@A@ABA@CAA?CCAE?AAABC@?BA?A@ABA@?@A@A@A?A@@??B@?@?@@@?BGNA@MA@A?CDAFCBE?CCEEACBEBED?@?H?BDBF?DCDCFA@IAGECGAE?CDCDA@E???AHDHD@FCBE@CBCBG?E?AGCEBEFGBA@CBBFBFFAF?BGDC@G@CCCEEG?A@EDEFCB?@@D@DD@FCDEBADGCGACCAG?A@GBEDA@?FBFB@F?B?DEBGBE?ACEECE?A@EDCDA@AD?@BDFBB?DCFEBC?CAEAEGCA@GBCDA@AB?@CF@DF@DAFCDE@EBG?AEEAAE@GBCDE@A@@F@BF@B?DABCDE?I?AEAEAGBCBED?@@F?BBBD?BA',
    startDate: '2021-07-08T13:42:00Z',
    startPosition: {
      lat: -23.559417,
      lng: -46.689646,
    },
    time: {
      elapsed: 967,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 1710,
    elevation: {
      gain: 0,
    },
    id: '5600804398',
    name: 'Corridinha quadra pt.2',
    pace: {
      average: 320,
    },
    polyline:
      'nmxnCxa~{G@B?@@B?@AD??A@?ACCC?A?C?A@A@CEFA@AIPDB@??KEEGEAAAD?BC@EBA?@F@BF?H?FC@EDABE@A?CACGECCA?ABA@A@A@CF?FBFF?DADEDGDABE?EGCCAIHAFE@A@EDAF?@BGLKFCDCEECCGCGFEDAH?F?FD@DAHK?GCEGAAAEBGD?D?@FD@?HABABCBECEA?E@EBA@C@E@A??F???B?BF?BCJIDG?EECE?CFCDA@E@?BCBA@AABCH?HADEBGAGA@A?@R???B???@@?BB@A@A?@@???@?E@@G@ABA?AC?AACA??AACB@DA@CDDA?CFC@A?GCEAGEAEBCDEDA@CBAHABAABGFGJCFCBEAGECG@EFAF?D@HDFF?HA@E?C@C?C?CECCEEAAHCFE?CBA@AD@FFDHEDEBE?EEEC?GCGAEBAD?BBDB@BBF?BCDCB??BE?AGEGAEAIAGEDAFCHADH@BAFEDC@?DCAEACGAE@CDADEDA@CB?@BFBA@C@ADCF?F@F@DB?@CAC?I@EBG?A?GCCBAFBBB@HEBGBC@ABG@AAGECCCEFEDABA?EDABCDA@?BB@LMFIDABC?@A?A@??EDA?E@?@A@@BDCDA@ADCBG@ACCA?AEG?A@EBA@ABCD@F@@FABADGDABE?GCCG?C?EBABEBCD?B?DF@DCDEBCBA?CCEE?EBEDABC@A?AFDDDAFEBCHIAEEAGBCDEBAF?@?F@@BCBCJCDEFEAGCAGAEBCFEDA?CD?@AD?@??BEDCBAFC@ABADE@ACCGAE?CDEDA@C@A@ABAF@@D?FADC@EDC@ABABCACAAECEBCFA@E@A@CD?@E@AD?@??FADCBADADC@?AGAAAAAAA?EBA?CFCBCD@FB@HCDEDGDE@ECCIAEFKJCH?F@DFIFIHI@EAE?ACCAACBA@EDA?CDA@CF?BD?FCBABAB?@AB?AAH@AC?AAAC@EBEBABGBA@AD@?HEFCDEDADC?AEECACAEAGDCDABA@AD@FBD@@JIDEDCAEAAG@C?EBC@EDABE@GACEAEACBEJE?ECBAB?H?BA@EB?FD?BADCDC@?BC??@A@AAA?@??',
    startDate: '2021-07-09T17:17:00Z',
    startPosition: {
      lat: -23.559443,
      lng: -46.689733,
    },
    time: {
      elapsed: 549,
    },
    type: 'Run',
  },
  {
    athleteId,
    distance: 1710,
    elevation: {
      gain: 0,
    },
    id: '5612194947',
    name: 'corridinja cansada de domingo',
    pace: {
      average: 331,
    },
    polyline:
      'bmxnCbb~{G?C???A@??A??@?BB?@A@A?A?EBA@C@C?ACBC@CDEDCDAB@BFADA@EBEBC?C@AAE?A?EG@K@EH?FDFFFBDB?FCDKA@GBC@IAE@EDA@@BE?A@D?DEDG?E@A?C@E?CAAADEDAFEFAB@@@AFCDKDEBE@CB?EACA?DADGBCDCD@@@@D?DEBEBE@E@CAAG?A?DCJBIBEDIBGDCBE@?@B@BCFADBC@A@C@ACE?@@B@B@D@JADW@?E@IF?B@AA@EJIBECCAAC?CAC@IFGDEHAFFEBE@CDE@AB@@??@?@A?A@??A@???@QD@?@???B?BA@ACAAAAAAAEDA@CBADA@?D?@FG@ADCDC@AA@ACC?CBEDA?CBA@EGCD??CC?CLGDC@E?AC?A@A@CDCF?@@DBDHCHGFEDCAICAA?EBEDCHCB@@BC@CHGFC??C@A@A@GF?HCBAB?B@B?@@??C@AAE?U?A@A??FE@ADB?D?HGFCBA?A@A@?A???EAEAEBALEDC@?HBDFCDC@G?CEECECAABCFADCB??@@DCHGBEDGBC@EE?MBK@GB??D@DAFCFEDABA?CE@GBG@C?E@AFCFADJAL?F?FEDCAAE?E?C@?@A@?DA?AIC??AA?C@ABA@@BD@BCDEBC@CBCAA?A?AEBEDCFADCDABF@@CFA@GBA@E@ECAA?HE?AEDEFEHAH?D@A@IDGBCBC@C?@@B?B?B?FEBDCDE?E@GCGE?C?EBIH?HCD?@F?@EDG?G@?HDDFA?ABMBGBGBB?B?DCBA@C@G@CAEEAE?EDE@?FA@A@?BADB?B?DEDI@C?A@C?CACCAAAEFEFAHADCBF?@CDCDCBGBEAA?CC?G?CHCDADAD?@@@DEDC@E?EBCDCF?@@CBCDGDCBC@AA@A@A?A@??EAA?',
    startDate: '2021-07-11T17:07:00Z',
    startPosition: {
      lat: -23.559381,
      lng: -46.689777,
    },
    time: {
      elapsed: 456,
    },
    type: 'Run',
  },
]

export default ste
